name: Build Documentation

on:
  push:  # 所有分支的推送都触发
  pull_request:
  workflow_dispatch:  # 保留手动触发选项

permissions:
  contents: write

jobs:
  build_doc:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y cmake graphviz bibtex2html
          sudo pip install lxml pyquery
          wget --no-verbose -O doxygen_exe https://cgal.geometryfactory.com/~cgaltest/doxygen_1_9_6_patched/doxygen
          sudo mv doxygen_exe /usr/bin/doxygen
          sudo chmod +x /usr/bin/doxygen

      - name: CMake configuration
        run: |
          mkdir -p build_doc
          cd build_doc
          cmake ../Documentation/doc -DBUILD_DOC=ON -DCGAL_GENERATE_XML=ON -DCGAL_DOC_CREATE_LOGS=ON

      - name: Build documentation
        run: |
          cd build_doc
          make -j$(nproc) doc
          make -j$(nproc) doc_with_postprocessing
          # 检查构建是否成功
          if [ ! -f "doc_output/Manual/index.html" ]; then
            echo "Error: Documentation build failed - index.html not found"
            exit 1
          fi

      - name: Create .nojekyll file
        run: |
          mkdir -p build_doc/doc_output/Manual
          touch build_doc/doc_output/Manual/.nojekyll

      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Current branch: $(git branch --show-current)"
          echo "Checking .nojekyll file:"
          ls -la build_doc/doc_output/Manual/.nojekyll

      - name: Check documentation output
        run: |
          echo "Checking documentation output directory:"
          ls -la build_doc/doc_output/Manual/
          echo "Checking for index.html:"
          find build_doc/doc_output/Manual/ -name "index.html"

      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/v6.0.1-cn'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_doc/doc_output/Manual
          force_orphan: true
          enable_jekyll: false
          commit_message: "Deploy documentation"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
