name: Build Documentation

on:
  push:  # 所有分支的推送都触发
  pull_request:
  workflow_dispatch:  # 保留手动触发选项

permissions:
  contents: write

jobs:
  build_doc:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y cmake graphviz bibtex2html
          pip install --user lxml pyquery
          wget --no-verbose -O doxygen_exe https://cgal.geometryfactory.com/~cgaltest/doxygen_1_9_6_patched/doxygen
          sudo mv doxygen_exe /usr/bin/doxygen
          sudo chmod +x /usr/bin/doxygen

      - name: Setup doxygen-awesome-css
        run: |
          mkdir -p Documentation/doc/doxygen-awesome-css
          # 克隆仓库并获取标签信息
          git clone --depth 1 --branch v2.3.4 https://github.com/jothepro/doxygen-awesome-css.git temp_repo
          # 复制需要的文件
          cp temp_repo/doxygen-awesome.css Documentation/doc/doxygen-awesome-css/
          cp temp_repo/doxygen-awesome-sidebar-only.css Documentation/doc/doxygen-awesome-css/
          rm -rf temp_repo

      - name: Check and setup theme
        id: check_theme
        run: |
          if [ -d "Documentation/doc/doxygen-awesome-css" ]; then
            echo "Using Doxygen Awesome theme"
            echo "has_theme=true" >> $GITHUB_OUTPUT
          else
            echo "Using default theme"
            echo "has_theme=false" >> $GITHUB_OUTPUT
          fi

      - name: CMake configuration
        run: |
          mkdir -p build_doc
          cd build_doc
          if [ "${{ steps.check_theme.outputs.has_theme }}" = "true" ]; then
            cmake ../Documentation/doc \
              -DBUILD_DOC=ON \
              -DCGAL_GENERATE_XML=ON \
              -DCGAL_DOC_CREATE_LOGS=ON \
              -DCGAL_PACKAGE_DOC_DIR=../Documentation/doc \
              -DOUTPUT_LANGUAGE=Chinese
          else
            cmake ../Documentation/doc \
              -DBUILD_DOC=ON \
              -DCGAL_GENERATE_XML=ON \
              -DCGAL_DOC_CREATE_LOGS=ON \
              -DOUTPUT_LANGUAGE=Chinese
          fi

      - name: Build documentation
        run: |
          cd build_doc
          make -j$(nproc) doc
          make -j$(nproc) doc_with_postprocessing
          # 检查构建是否成功
          if [ ! -f "doc_output/Manual/index.html" ]; then
            echo "Error: Documentation build failed - index.html not found"
            exit 1
          fi

      - name: Create .nojekyll and redirect index
        run: |
          cd build_doc/doc_output
          # 创建 .nojekyll 文件
          touch .nojekyll
          # 创建根目录的 index.html 重定向到 Manual/index.html
          echo '<meta http-equiv="refresh" content="0; url=Manual/index.html">' > index.html

      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Current branch: $(git branch --show-current)"
          echo "Checking files:"
          ls -la build_doc/doc_output/
          ls -la build_doc/doc_output/Manual/

      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/v6.0.1-cn'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_doc/doc_output
          force_orphan: true
          enable_jekyll: false
          commit_message: "Deploy documentation"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Verify theme files
        run: |
          echo "Checking theme files:"
          ls -la Documentation/doc/doxygen-awesome-css/
          echo "Checking if theme files exist:"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome.css || echo "Missing main CSS"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome-sidebar-only.css || echo "Missing sidebar CSS"
          test -f Documentation/doc/doxygen-awesome-css/header.html || echo "Missing header"
