name: Build Documentation

on:
  push:  # 所有分支的推送都触发
  pull_request:
  workflow_dispatch:  # 保留手动触发选项

permissions:
  contents: write

jobs:
  build_doc:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y cmake graphviz bibtex2html
          pip install --user lxml pyquery
          wget --no-verbose -O doxygen_exe https://cgal.geometryfactory.com/~cgaltest/doxygen_1_9_6_patched/doxygen
          sudo mv doxygen_exe /usr/bin/doxygen
          sudo chmod +x /usr/bin/doxygen

      - name: Setup doxygen-awesome-css
        run: |
          mkdir -p Documentation/doc/doxygen-awesome-css
          # 克隆仓库并获取标签信息
          git clone --depth 1 --branch v2.3.4 https://github.com/jothepro/doxygen-awesome-css.git temp_repo

          # 复制主题文件
          cp temp_repo/doxygen-awesome.css Documentation/doc/doxygen-awesome-css/
          cp temp_repo/doxygen-awesome-sidebar-only.css Documentation/doc/doxygen-awesome-css/
          cp temp_repo/doxygen-awesome-darkmode-toggle.js Documentation/doc/doxygen-awesome-css/
          cp temp_repo/doxygen-awesome-fragment-copy-button.js Documentation/doc/doxygen-awesome-css/
          cp temp_repo/doxygen-awesome-paragraph-link.js Documentation/doc/doxygen-awesome-css/
          cp temp_repo/doxygen-awesome-interactive-toc.js Documentation/doc/doxygen-awesome-css/

          # 创建自定义 header.html
          cat > Documentation/doc/doxygen-awesome-css/header.html << 'EOF'
          <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
          <html xmlns="http://www.w3.org/1999/xhtml" lang="$langISO">
          <head>
            <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
            <meta http-equiv="X-UA-Compatible" content="IE=11"/>
            <meta name="generator" content="Doxygen $doxygenversion"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <!--BEGIN PROJECT_NAME--><title>$projectname: $title</title><!--END PROJECT_NAME-->
            <!--BEGIN !PROJECT_NAME--><title>$title</title><!--END !PROJECT_NAME-->
            <link href="$relpath^tabs.css" rel="stylesheet" type="text/css"/>
            <!--BEGIN DISABLE_INDEX-->
              <!--BEGIN FULL_SIDEBAR-->
              <script type="text/javascript">var page_layout=1;</script>
              <!--END FULL_SIDEBAR-->
            <!--END DISABLE_INDEX-->
            <script type="text/javascript" src="$relpath^jquery.js"></script>
            <script type="text/javascript" src="$relpath^dynsections.js"></script>
            $treeview
            $search
            $mathjax
            $darkmode
            $doxygen_awesome_css
            $doxygen_awesome_sidebar_only_css
            $extrastylesheet
            <script type="text/javascript" src="$relpath^doxygen-awesome-darkmode-toggle.js"></script>
            <script type="text/javascript" src="$relpath^doxygen-awesome-fragment-copy-button.js"></script>
            <script type="text/javascript" src="$relpath^doxygen-awesome-paragraph-link.js"></script>
            <script type="text/javascript" src="$relpath^doxygen-awesome-interactive-toc.js"></script>
            <script type="text/javascript">
                DoxygenAwesomeDarkModeToggle.init()
                DoxygenAwesomeFragmentCopyButton.init()
                DoxygenAwesomeParagraphLink.init()
                DoxygenAwesomeInteractiveToc.init()
            </script>
          </head>
          <body>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
          EOF

          rm -rf temp_repo

      - name: Check and setup theme
        id: check_theme
        run: |
          if [ -d "Documentation/doc/doxygen-awesome-css" ]; then
            echo "Using Doxygen Awesome theme"
            echo "has_theme=true" >> $GITHUB_OUTPUT
          else
            echo "Using default theme"
            echo "has_theme=false" >> $GITHUB_OUTPUT
          fi

      - name: CMake configuration
        run: |
          mkdir -p build_doc
          cd build_doc
          if [ "${{ steps.check_theme.outputs.has_theme }}" = "true" ]; then
            cmake ../Documentation/doc \
              -DBUILD_DOC:BOOL=ON \
              -DCGAL_GENERATE_XML:BOOL=ON \
              -DCGAL_DOC_CREATE_LOGS:BOOL=ON \
              -DCGAL_PACKAGE_DOC_DIR:PATH=../Documentation/doc
          else
            cmake ../Documentation/doc \
              -DBUILD_DOC:BOOL=ON \
              -DCGAL_GENERATE_XML:BOOL=ON \
              -DCGAL_DOC_CREATE_LOGS:BOOL=ON
          fi

      - name: Build documentation
        run: |
          cd build_doc
          make -j$(nproc) doc
          make -j$(nproc) doc_with_postprocessing
          # 检查构建是否成功
          if [ ! -f "doc_output/Manual/index.html" ]; then
            echo "Error: Documentation build failed - index.html not found"
            exit 1
          fi

      - name: Create .nojekyll and redirect index
        run: |
          cd build_doc/doc_output
          # 创建 .nojekyll 文件
          touch .nojekyll
          # 创建根目录的 index.html 重定向到 Manual/index.html
          echo '<meta http-equiv="refresh" content="0; url=Manual/index.html">' > index.html

      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Current branch: $(git branch --show-current)"
          echo "Checking files:"
          ls -la build_doc/doc_output/
          ls -la build_doc/doc_output/Manual/

      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/v6.0.1-cn'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_doc/doc_output
          force_orphan: true
          enable_jekyll: false
          commit_message: "Deploy documentation"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Verify theme files
        run: |
          echo "Checking theme files:"
          ls -la Documentation/doc/doxygen-awesome-css/
          echo "Checking if theme files exist:"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome.css || echo "Missing main CSS"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome-sidebar-only.css || echo "Missing sidebar CSS"
          test -f Documentation/doc/doxygen-awesome-css/header.html || echo "Missing header"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js || echo "Missing darkmode JS"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome-fragment-copy-button.js || echo "Missing copy button JS"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome-paragraph-link.js || echo "Missing paragraph link JS"
          test -f Documentation/doc/doxygen-awesome-css/doxygen-awesome-interactive-toc.js || echo "Missing interactive TOC JS"
