name: Build Documentation

on:
  push:  # 所有分支的推送都触发
  pull_request:
  workflow_dispatch:  # 保留手动触发选项

permissions:
  contents: write

jobs:
  build_doc:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y cmake graphviz bibtex2html
          sudo pip install lxml pyquery
          wget --no-verbose -O doxygen_exe https://cgal.geometryfactory.com/~cgaltest/doxygen_1_9_6_patched/doxygen
          sudo mv doxygen_exe /usr/bin/doxygen
          sudo chmod +x /usr/bin/doxygen

      - name: CMake configuration
        run: |
          mkdir -p build_doc
          cd build_doc
          cmake ../Documentation/doc

      - name: Build documentation
        run: |
          cd build_doc
          make -j$(nproc) doc
          make -j$(nproc) doc_with_postprocessing

      - name: Create .nojekyll file
        run: |
          touch build_doc/doc_output/.nojekyll

      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/v6.0.1-cn'  # 在 v6.0.1-cn 分支推送时部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_doc/doc_output
          force_orphan: true
          enable_jekyll: false  # 确保禁用 Jekyll
